tests/ExceptionHandlerTest.php, tests/Exceptions/AbstractExceptionTest.php, tests/Exceptions/ExceptionsTest.php, tests/Filters/QueryFilterTest.php, tests/Http/PaginatorTest.php, tests/Resources/CollectionResourcesTest.php, tests/Resources/PromiseCollectionResourcesTest.php, tests/Resources/QueryResourcesTest.php, tests/Stubs/TransformerStub.php, tests/Traits/TimestampsTraitTest.php, tests/Transformers/AbstractTransformerTest.php, tests/Transformers/TransformerCollectionTest.php, tests/Transformers/TransformerFactoryTest.php, tests/Transformers/TransformerItemTest.php, tests/Transformers/TransformerResourceTest.php, tests/Transformers/TransformerServiceTest.php
Code coverage from `52.49%` to `84.79%`
=> MP-219 ✅ tests for exceptions, resources and transformers

src/Exceptions/Interfaces/ExceptionInterface.php, src/Exceptions/MissingBillingInformationException.php, src/Exceptions/PaymentRequiredException.php
**Changes**
- Added PaymentRequiredException
- Added new error code range for billing/payment related errors.
=> Added PaymentRequiredException.

src/Http/Paginator.php, src/Http/Traits/RequestTrait.php, src/Transformers/TransformerService.php, tests/Http/PaginatorTest.php, tests/Transformers/TransformerServiceTest.php
- Task: https://myparcelcombv.atlassian.net/browse/MP-1334
=> Allow higher max record size

src/Http/Paginator.php, tests/Http/PaginatorTest.php
Issue: https://myparcelcombv.atlassian.net/browse/MP-1334
=> Min values now fallback to 30

src/Exceptions/AbstractMultiErrorException.php
**Changes**
- Added required parameters to constructor of multi error exception
=> Add missing attributes to error classes

src/Exceptions/AbstractException.php, src/Exceptions/AbstractMultiErrorException.php, src/Exceptions/GenericCarrierException.php, src/Exceptions/Interfaces/JsonSchemaErrorInterface.php, src/Exceptions/Interfaces/MultiErrorInterface.php, src/Exceptions/InvalidCredentialsException.php, src/Exceptions/InvalidInputException.php, tests/Exceptions/AbstractExceptionTest.php, tests/Exceptions/ExceptionsTest.php
**Changes**
- Changed type of `$status` in exceptions to integer
- Added a couple of exceptions that extend the `AbstractMultiErrorException`
=> Add multi error exceptions

src/ExceptionHandler.php, src/Exceptions/CarrierDataNotFoundException.php, src/Filters/Interfaces/FilterInterface.php, src/Http/Traits/RequestTrait.php, src/Traits/AssertionsTrait.php, tests/ExceptionHandlerTest.php, tests/Exceptions/ExceptionsTest.php, tests/Filters/QueryFilterTest.php, tests/Http/PaginatorTest.php, tests/Mocks/AssertionsMock.php, tests/Resources/QueryResourcesTest.php, tests/Stubs/TransformerStub.php, tests/Traits/AssertionsTraitTest.php, tests/Transformers/TransformerServiceTest.php
**Changes**
- Added `CarrierDataNotFoundException`.
- Added missing tests.
- Made `assertJsonDataContainsIds` public.
=> Added CarrierDataNotFoundException

src/ExceptionHandler.php, src/Exceptions/Interfaces/JsonSchemaErrorInterface.php
**Changes**
- Added debug with stack trace to meta of MultiErrorExceptions.
=> Added debug with trace to MultiErrorExceptions.

src/Transformers/TransformerItem.php
**Related Issues**
- https://myparcelcombv.atlassian.net/browse/MP-2013
=> MP-2013 Fix optional relationship include bug

composer.json, composer.lock, phpunit.xml, tests/Filters/QueryFilterTest.php
https://myparcelcombv.atlassian.net/browse/DO-64
- Updated phpunit and related packages.
- Fixed test.
=> DO-64 - Update phpunit

src/ExceptionHandler.php
**Changes**
- Added array_filter to remove null meta in response of multiErrorException.
**Related Issues**
- None
=> 🐛 Added array_filter to remove null meta in response

src/ExceptionHandler.php, src/Exceptions/Interfaces/ExceptionInterface.php, src/Exceptions/TooManyRequestsException.php, tests/ExceptionHandlerTest.php, tests/Exceptions/ExceptionsTest.php
**Changes**
- Added ThrottleRequestsException handling
- Added TooManyRequestsException that responds to ThrottleRequestsException. 
**Related Issues**
- [MP-2541](https://myparcelcombv.atlassian.net/browse/MP-2541) Subtask
- [MP-2508](https://myparcelcombv.atlassian.net/browse/MP-2508) Story
=> MP-2541 Too many requests exception

src/Transformers/AbstractTransformer.php, src/Transformers/TransformerInterface.php, src/Transformers/TransformerService.php
- Needed for: https://myparcelcombv.atlassian.net/browse/MP-2286
=> Added missing setters for transformer

src/Transformers/TransformerService.php, tests/Transformers/TransformerServiceTest.php
@M4tini Can you make a release of this?
=> Removed required parameter from transformer service

src/Exceptions/Interfaces/ExceptionInterface.php, src/Exceptions/RelationshipCannotBeModifiedException.php, tests/Exceptions/ExceptionsTest.php
**Changes**
- Added `RelationshipCannotBeModifiedException`.
- Updated code of the `TOO_MANY_REQUESTS` error because it had the same one as the `MISSING_REQUEST_HEADER` error.
=> Added RelationshipCannotBeModifiedException.

src/Transformers/AbstractTransformer.php, src/Transformers/TransformerInterface.php, tests/Mocks/Transformers/FatherTransformerMock.php, tests/Mocks/Transformers/MotherTransformerMock.php, tests/Mocks/Transformers/PersonTransformerMock.php, tests/Transformers/AbstractTransformerTest.php
**Changes**
- Added meta flag to transformIdentifier method.
=> Added flag for adding meta in transforming identifiers.

composer.lock, tests/Errors/GenericCarrierErrorTest.php, tests/Exceptions/ExceptionsTest.php, tests/Stubs/TransformerStub.php, tests/Transformers/AbstractTransformerTest.php, tests/Transformers/TransformerItemTest.php, tests/Transformers/TransformerServiceTest.php
- Updated packages.
- Added some tests.
=> ✅ Added tests

src/Transformers/TransformerItem.php
- Fixed issue where the included relationship was null.
=> :bug: support including of null relationships

composer.lock, src/Transformers/TransformerFactory.php
Fixes: https://github.com/MyParcelCOM/json-api/network/alerts
=> ⬆️ Updated packages

composer.json, composer.lock, src/ExceptionHandler.php, src/Resources/PromiseCollectionResources.php, src/Traits/AssertionsTrait.php, tests/ExceptionHandlerTest.php, tests/Exceptions/AbstractExceptionTest.php, tests/Http/Traits/RequestTraitTest.php, tests/Transformers/TransformerCollectionTest.php
- Muted some exceptions.
- Removed NewRelic.
=> 🔥 Removed newrelic

src/ExceptionHandler.php
- https://myparcelcombv.atlassian.net/browse/MP-3230
Added logging of the individual errors in the context of the error.
=> Added multi error errors to log context in ExceptionHandler.

composer.lock, src/Http/Paginator.php, src/Traits/AssertionsTrait.php, tests/Http/PaginatorTest.php
https://myparcelcombv.atlassian.net/browse/MP-2922
=> MP-2922 🐛 Respect max page size

src/Transformers/AbstractTransformer.php
- QA task: https://myparcelcombv.atlassian.net/browse/MP-3553
- Main task: https://myparcelcombv.atlassian.net/browse/MP-3535
=> MP-3553 Deep filter empty meta

src/ExceptionHandler.php
https://laravel.com/docs/7.x/upgrade#symfony-5-related-upgrades
=> 🐛 Accept throwable instead of exception

src/Filters/Traits/AppliesFiltersTrait.php
Port functionality from `ShipmentRepository` to use in other repositories.
- Array dot notation to support nested filters.
- Support date filtering using `<=` and `>=`.
=> 🚚 Port shipment date filter helper

composer.json, composer.lock, docker-compose.yml, docker/Dockerfile, mp.sh, mp/test, phpunit.xml, tests/Transformers/TransformerCollectionTest.php
- Added support for PHP 8.0
- Added support for Laravel 8.0
- Updated phpunit version + new formatted config file
- Updated to composer 2.0
- Added proper user permissions for docker-compose
- Unmocked Iterator :skull_and_crossbones:
=> ⬆️ Upgraded dependencies to allow PHP >= 8.0 and Laravel 8.0

composer.lock, src/Exceptions/ForbiddenException.php, src/Exceptions/Interfaces/ExceptionInterface.php, tests/Exceptions/ExceptionsTest.php
- Introduced the ForbiddenException.
- Updated packages.
=> Forbidden exception

src/Filters/Traits/AppliesFiltersTrait.php, tests/Filters/AppliesFiltersTraitTest.php
- Allow timestamps in date filters to allow for more specific filtering
- https://myparcelcombv.atlassian.net/browse/MP-4687
=> MP-4687 Allow timestamps in date filters.

src/ExceptionHandler.php
This will allow for the context to be overriden
=> ♻️ Extract report context creation in a function

.github/workflows/ci.yml, composer.lock, src/ExceptionHandler.php, src/Traits/AssertionsTrait.php, tests/ExceptionHandlerTest.php
https://myparcelcombv.atlassian.net/browse/MP-5456
---
Instead of logging 1 error with `Response contains multiple errors` and the actual error(s) in the `multi_error_errors` context, we now report each JsonSchemaError as a separate error.
=> 🔊 Report multi-error errors separately

src/ExceptionHandler.php, src/Exceptions/Interfaces/ExceptionInterface.php, src/Exceptions/ResourceHandledBy3rdPartyException.php, tests/Exceptions/ExceptionsTest.php
https://myparcelcombv.atlassian.net/browse/MP-6509
=> :sparkles: Introduced new exception resource handled by 3rd party

composer.lock, docker-compose.yml, src/Transformers/TransformerFactory.php, src/Transformers/TransformerInterface.php, tests/ExceptionHandlerTest.php
This change is backwards compatible and allows us to have proper constructor injection in our Transformer classes.
=> 🚸 Use Laravel to make new instances of transformers
