MyParcelCOM/json-api

- src/ExceptionHandler.php
- tests/ExceptionHandlerTest.php
When logging an exception, the entire trace was merged with the remaining context, which causes the logs to be unreadable.
Please release this as v0.4.3.
> ✨ When logging exceptions put stack trace in it's own array entry

- src/Exceptions/CarrierApiException.php
- tests/Exceptions/ExceptionsTest.php
**Changes**
- Added `carrier_status` to CarrierApiException meta.
**Related Issues**
- https://myparcelcombv.atlassian.net/browse/MP-1455
> MP-1455 Added carrier_status to CarrierApiException meta.

- src/ExceptionHandler.php
- src/Exceptions/Interfaces/ExceptionInterface.php
- src/Exceptions/MethodNotAllowedException.php
- tests/ExceptionHandlerTest.php
- tests/Exceptions/ExceptionsTest.php
**Changes**
- Map the `MethodNotAllowedHttpException` thrown by Laravel to a custom `MethodNotAllowedException`
**Related issues**
- https://myparcelcombv.atlassian.net/browse/MP-1373
> Map method not allowed exception

- src/Filters/Traits/AppliesFiltersTrait.php
**Changes**
- Filter empty filter values to prevent SQL errors (PostGres does not like `IN ('')`
> Filter empty values from filter values

- src/Transformers/ErrorTransformer.php
- tests/Transformers/ErrorTransformerTest.php
The `status` attribute in an error response was an `integer` while according to the [json-api specification](https://jsonapi.org/format/#errors) it should be a `string`.
Also added a test to make sure exceptions are correctly transformed.
> Fixed incorrect error status type

- composer.json
- composer.lock
- Reverted laravel dependency because this package can still be used in 5.4 projects.
> :arrow_down: reverted laravel dependency

- src/ExceptionHandler.php
The Laravel exception handler will ignore a bunch of exception classes that are either:
- validation exceptions
- authorization exceptions 
- not interesting exceptions (client-oriented exceptions)
We are only interested in reportable exceptions from our applications, therefore we can filter the not interesting ones using `shouldntReport` method from Laravel (which should have been called anyway)
> 🔇 Disabled reporting on exceptions that shouldn't be reported

- src/ExceptionHandler.php
- src/Resources/ResourceIdentifier.php
- src/Transformers/AbstractTransformer.php
- src/Transformers/TransformerCollection.php
- src/Transformers/TransformerItem.php
- src/Transformers/TransformerResource.php
- tests/Stubs/TransformerStub.php
- tests/Transformers/TransformerServiceTest.php
https://myparcelcombv.atlassian.net/browse/MP-2642
- Added filtering of the required `includes` to avoid duplicate database queries.
- Added `parentId` to `ResourceIdentifier` to transform links with multiple ID's.
The `getFilteredIncludes()` is actually revived from PR https://github.com/MyParcelCOM/json-api/pull/31 where it was deleted.
> MP-2642 ⚡️ Optimize including of resources

- src/ExceptionHandler.php
- tests/ExceptionHandlerTest.php
- https://myparcelcombv.atlassian.net/browse/MP-3339
We cannot blindly assume that every thrown exception has a status code related to it, since not all Exceptions are request exceptions. All (or most..?) of the Exceptions defined in this package implement the JsonSchemaErrorInterface, which includes the getStatus() method. In the API however, we also throw the Guzzle/RequestException. This method doesn't have the getStatus() method, and so we will have to make some additional changes in our API code to make sure this isn't logged.
> 🚑 Silence non-5xx errors in Rollbar

- src/Http/Traits/RequestTrait.php
- tests/Http/Traits/RequestTraitTest.php
`filter[sender_address][country_code]=` resulted in 0 records, because the column was filtered on an empty string.
> ♿️ Deep filter request filters

- composer.lock
- src/Traits/TimestampsTrait.php
- tests/Traits/TimestampsTraitTest.php
Laravel timestamp columns are instantiated as Carbon instances by default.
This fixes the type hinting in PhpStorm.
> 🐛 Return carbon for timestamps

- src/ExceptionHandler.php
- tests/ExceptionHandlerTest.php
Sometimes simple exceptions don't really have a stack trace (like PHP type errors): https://rollbar.com/myparcelcom/microservice-dhl-de/items/11/
This is because PHP code is loaded, not executed yet and PHP cannot make sense of something (like a strict return type and void returned). In these cases the exception has a file and line of code. This information is missing in our reporting.
Json-api package should be updated to include this information always.
- Added exception file and line when reporting
- Fixed tests
We should still discuss this solution, I added something from myself. My suggestion (see in code) is to include the file path and line where the exception occurred. This will be handy for many cases. However, it might also be annoying. Example would be: 
> There was a problem …
> 🔊 Expanded context on error reporting

- src/Http/Interfaces/RequestInterface.php
Fix: Declaration of `Illuminate\Http\Request::fullUrl()` must be compatible with
`MyParcelCom\JsonApi\Http\Interfaces\RequestInterface::fullUrl(): string`
> 🚑️ RequestInterface fullUrl needs to fit Illuminate\Http\Request

- src/Traits/AssertionsTrait.php
Without this change, we are limited to validate `application/vnd.api+json` responses only.
> ♻️ Respect accept header during validation

- src/ExceptionHandler.php
No need to log these errors, they are caused by external changes and already presented to the user in some way.
> 🔇 Dont report invalid credentials exception

- src/Filters/Traits/AppliesFiltersTrait.php
- Adjusted the regular expression for ISO 8601 formatted dates to also allow for Zulu time indicator and millseconds.
- Further adjustments were made to make sure that valid dates and times are passed.
> ♻️ Tweaked the ISO 8601 regex to allow for Zulu and milliseconds.

- src/Filters/Traits/AppliesFiltersTrait.php
- tests/Filters/AppliesFiltersTraitTest.php
The `date_from`  regex has been adjusted to support milliseconds and a negative timezone offset.
> 🐛 Support ISO date filter with negative timezone

- src/Http/Traits/RequestTrait.php
- src/Traits/ArrayFilterTrait.php
- src/Transformers/AbstractTransformer.php
This PR is opened because I want to use the `arrayDeepFilter()` functionality outside of this class.
It also seems that this repository already had 2 separate `arrayDeepFilter()` functions which did practically the same thing.
The small differences: the request one also filtered empty strings, while the transformer one removed leftover empty arrays.
Both use cases actually benefit from each others functionality, so our new `arrayDeepFilter()` trait does both!
> 🪆 Make arrayDeepFilter() available through a trait

- src/Transformers/AbstractTransformer.php
- src/Transformers/TransformerInterface.php
- tests/Stubs/TransformerStub.php
Transforming models that have not yet been persisted should also be possible.
> 🐛 Allow transformed model id to be null

- src/Exceptions/InvalidScopeException.php
- src/Exceptions/MissingScopeException.php
Make the scope exceptions support enums and strings.
> ♻️ Scope slugs can be enums

- src/Resources/ResourceIdentifier.php
- src/Transformers/AbstractTransformer.php
- tests/Stubs/TransformerStub.php
Since https://github.com/MyParcelCOM/json-api/pull/121 the type can be an enum or a string, but there are a few other functions that should start supporting this.
> ♻️ Accept UnitEnum or string for resource functions
